SHAPES = ["arrow", "turtle", "circle", "square", "triangle", "classic"]
COLORS = [
    "red",
    "orange",
    "yellow",
    "green",
    "blue",
    "purple",
    "pink",
    "brown",
    "black",
    "white",
    "gray",
    "cyan",
    "magenta",
    "gold",
    "navy",
    "maroon",
    "violet",
    "turquoise",
    "salmon",
    "coral",
    "khaki",
    "lavender",
    "tomato",
    "chocolate",
]
