[project]
name = "100-days-of-python"
version = "0.1.0"
description = "This repository contains all the tasks I've done for 100 days of Python"
readme = "README.md"
authors = [
    { name = "Juan Acosta", email = "acosta.juan@icloud.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.1.1",
]
